{
  "contributors": null,
  "coordinates": null,
  "created_at": "Thu Mar 19 21:11:43 +0000 2020",
  "entities": {
    "hashtags": [
      {
        "indices": [
          16,
          34
        ],
        "text": "instaprintmytweet"
      }
    ],
    "symbols": [],
    "urls": [],
    "user_mentions": [
      {
        "id": 1144249501647069200,
        "id_str": "1144249501647069185",
        "indices": [
          3,
          14
        ],
        "name": "kaaroClips",
        "screen_name": "ClipsKaaro"
      }
    ]
  },
  "favorite_count": 0,
  "favorited": false,
  "filter_level": "low",
  "geo": null,
  "hasBeenProcessed": false,
  "id": 1240747804387094500,
  "id_str": "1240747804387094529",
  "in_reply_to_screen_name": null,
  "in_reply_to_status_id": null,
  "in_reply_to_status_id_str": null,
  "in_reply_to_user_id": null,
  "in_reply_to_user_id_str": null,
  "is_quote_status": false,
  "lang": "en",
  "place": null,
  "quote_count": 0,
  "reply_count": 0,
  "retweet_count": 0,
  "retweeted": false,
  "retweeted_status": {
    "contributors": null,
    "coordinates": null,
    "created_at": "Tue Mar 17 10:03:40 +0000 2020",
    "entities": {
      "hashtags": [
        {
          "indices": [
            0,
            18
          ],
          "text": "instaprintmytweet"
        }
      ],
      "symbols": [],
      "urls": [],
      "user_mentions": []
    },
    "favorite_count": 0,
    "favorited": false,
    "filter_level": "low",
    "geo": null,
    "id": 1239854907819061200,
    "id_str": "1239854907819061253",
    "in_reply_to_screen_name": null,
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "in_reply_to_user_id": null,
    "in_reply_to_user_id_str": null,
    "is_quote_status": false,
    "lang": "en",
    "place": null,
    "quote_count": 0,
    "reply_count": 0,
    "retweet_count": 1,
    "retweeted": false,
    "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
    "text": "#instaprintmytweet how does this look?",
    "truncated": false,
    "user": {
      "contributors_enabled": false,
      "created_at": "Thu Jun 27 14:21:55 +0000 2019",
      "default_profile": true,
      "default_profile_image": false,
      "description": "Top and latest clips from Twitch! \nGGs all the way",
      "favourites_count": 9,
      "follow_request_sent": null,
      "followers_count": 6,
      "following": null,
      "friends_count": 31,
      "geo_enabled": false,
      "id": 1144249501647069200,
      "id_str": "1144249501647069185",
      "is_translator": false,
      "lang": null,
      "listed_count": 0,
      "location": null,
      "name": "kaaroClips",
      "notifications": null,
      "profile_background_color": "F5F8FA",
      "profile_background_image_url": "",
      "profile_background_image_url_https": "",
      "profile_background_tile": false,
      "profile_image_url": "http://pbs.twimg.com/profile_images/1144249582819454976/AC1p8N7T_normal.jpg",
      "profile_image_url_https": "https://pbs.twimg.com/profile_images/1144249582819454976/AC1p8N7T_normal.jpg",
      "profile_link_color": "1DA1F2",
      "profile_sidebar_border_color": "C0DEED",
      "profile_sidebar_fill_color": "DDEEF6",
      "profile_text_color": "333333",
      "profile_use_background_image": true,
      "protected": false,
      "screen_name": "ClipsKaaro",
      "statuses_count": 729,
      "time_zone": null,
      "translator_type": "none",
      "url": null,
      "utc_offset": null,
      "verified": false
    }
  },
  "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
  "streamTrackerLabel": "instaprintmytweet",
  "text": "RT @ClipsKaaro: #instaprintmytweet how does this look?",
  "timestamp_ms": "1584652303202",
  "truncated": false,
  "user": {
    "contributors_enabled": false,
    "created_at": "Thu Jun 27 14:21:55 +0000 2019",
    "default_profile": true,
    "default_profile_image": false,
    "description": "Top and latest clips from Twitch! \nGGs all the way",
    "favourites_count": 9,
    "follow_request_sent": null,
    "followers_count": 6,
    "following": null,
    "friends_count": 31,
    "geo_enabled": false,
    "id": 1144249501647069200,
    "id_str": "1144249501647069185",
    "is_translator": false,
    "lang": null,
    "listed_count": 0,
    "location": null,
    "name": "kaaroClips",
    "notifications": null,
    "profile_background_color": "F5F8FA",
    "profile_background_image_url": "",
    "profile_background_image_url_https": "",
    "profile_background_tile": false,
    "profile_image_url": "http://pbs.twimg.com/profile_images/1144249582819454976/AC1p8N7T_normal.jpg",
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/1144249582819454976/AC1p8N7T_normal.jpg",
    "profile_link_color": "1DA1F2",
    "profile_sidebar_border_color": "C0DEED",
    "profile_sidebar_fill_color": "DDEEF6",
    "profile_text_color": "333333",
    "profile_use_background_image": true,
    "protected": false,
    "screen_name": "ClipsKaaro",
    "statuses_count": 730,
    "time_zone": null,
    "translator_type": "none",
    "url": null,
    "utc_offset": null,
    "verified": false
  }
}